/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamLoginRouteImport } from './routes/team-login'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationRouteImport } from './routes/location'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamIndexRouteImport } from './routes/team.index'
import { Route as TeamWithdrawRouteImport } from './routes/team.withdraw'
import { Route as TeamProfileRouteImport } from './routes/team.profile'
import { Route as TeamPaymentsRouteImport } from './routes/team.payments'
import { Route as TeamLeaderboardRouteImport } from './routes/team.leaderboard'
import { Route as TeamEarningsRouteImport } from './routes/team.earnings'
import { Route as TeamEarningInfoRouteImport } from './routes/team.earning-info'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBusinessRouteImport } from './routes/_authenticated/business'
import { Route as AuthenticatedAffiliateRouteImport } from './routes/_authenticated/affiliate'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedBusinessIndexRouteImport } from './routes/_authenticated/business.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedDashboardSupportRouteImport } from './routes/_authenticated/dashboard.support'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardSessionsRouteImport } from './routes/_authenticated/dashboard.sessions'
import { Route as AuthenticatedDashboardBillingRouteImport } from './routes/_authenticated/dashboard.billing'
import { Route as AuthenticatedBusinessWithdrawalsRouteImport } from './routes/_authenticated/business.withdrawals'
import { Route as AuthenticatedBusinessUrlsRouteImport } from './routes/_authenticated/business.urls'
import { Route as AuthenticatedBusinessTeamsRouteImport } from './routes/_authenticated/business.teams'
import { Route as AuthenticatedBusinessTeamEarningsRouteImport } from './routes/_authenticated/business.team-earnings'
import { Route as AuthenticatedBusinessRulesRouteImport } from './routes/_authenticated/business.rules'
import { Route as AuthenticatedBusinessRecruitmentRouteImport } from './routes/_authenticated/business.recruitment'
import { Route as AuthenticatedBusinessMembersRouteImport } from './routes/_authenticated/business.members'
import { Route as AuthenticatedBusinessMemberPayoutsRouteImport } from './routes/_authenticated/business.member-payouts'
import { Route as AuthenticatedBusinessLeaderboardRouteImport } from './routes/_authenticated/business.leaderboard'
import { Route as AuthenticatedBusinessEarningsRouteImport } from './routes/_authenticated/business.earnings'
import { Route as AuthenticatedBusinessActivityRouteImport } from './routes/_authenticated/business.activity'
import { Route as AuthenticatedAdminVersionsRouteImport } from './routes/_authenticated/admin.versions'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminTicketsRouteImport } from './routes/_authenticated/admin.tickets'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminSessionsRouteImport } from './routes/_authenticated/admin.sessions'
import { Route as AuthenticatedAdminPlatformsRouteImport } from './routes/_authenticated/admin.platforms'
import { Route as AuthenticatedAdminPlansRouteImport } from './routes/_authenticated/admin.plans'
import { Route as AuthenticatedAdminPlanInfoRouteImport } from './routes/_authenticated/admin.plan-info'
import { Route as AuthenticatedAdminPayoutsRouteImport } from './routes/_authenticated/admin.payouts'
import { Route as AuthenticatedAdminPayoutMethodsRouteImport } from './routes/_authenticated/admin.payout-methods'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminOffersRouteImport } from './routes/_authenticated/admin.offers'
import { Route as AuthenticatedAdminFeaturesRouteImport } from './routes/_authenticated/admin.features'
import { Route as AuthenticatedAdminContactRouteImport } from './routes/_authenticated/admin.contact'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin.announcements'
import { Route as AuthenticatedAdminAffiliateRouteImport } from './routes/_authenticated/admin.affiliate'

const TeamLoginRoute = TeamLoginRouteImport.update({
  id: '/team-login',
  path: '/team-login',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamRoute,
} as any)
const TeamWithdrawRoute = TeamWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => TeamRoute,
} as any)
const TeamProfileRoute = TeamProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TeamRoute,
} as any)
const TeamPaymentsRoute = TeamPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => TeamRoute,
} as any)
const TeamLeaderboardRoute = TeamLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => TeamRoute,
} as any)
const TeamEarningsRoute = TeamEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => TeamRoute,
} as any)
const TeamEarningInfoRoute = TeamEarningInfoRouteImport.update({
  id: '/earning-info',
  path: '/earning-info',
  getParentRoute: () => TeamRoute,
} as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusinessRoute = AuthenticatedBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAffiliateRoute = AuthenticatedAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedBusinessIndexRoute =
  AuthenticatedBusinessIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBusinessRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedDashboardSupportRoute =
  AuthenticatedDashboardSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSessionsRoute =
  AuthenticatedDashboardSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBillingRoute =
  AuthenticatedDashboardBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedBusinessWithdrawalsRoute =
  AuthenticatedBusinessWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => AuthenticatedBusinessRoute,
  } as any)
const AuthenticatedBusinessUrlsRoute =
  AuthenticatedBusinessUrlsRouteImport.update({
    id: '/urls',
    path: '/urls',
    getParentRoute: () => AuthenticatedBusinessRoute,
  } as any)
const AuthenticatedBusinessTeamsRoute =
  AuthenticatedBusinessTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => AuthenticatedBusinessRoute,
  } as any)
const AuthenticatedBusinessTeamEarningsRoute =
  AuthenticatedBusinessTeamEarningsRouteImport.update({
    id: '/team-earnings',
    path: '/team-earnings',
    getParentRoute: () => AuthenticatedBusinessRoute,
  } as any)
const AuthenticatedBusinessRulesRoute =
  AuthenticatedBusinessRulesRouteImport.update({
    id: '/rules',
    path: '/rules',
    getParentRoute: () => AuthenticatedBusinessRoute,
  } as any)
const AuthenticatedBusinessRecruitmentRoute =
  AuthenticatedBusinessRecruitmentRouteImport.update({
    id: '/recruitment',
    path: '/recruitment',
    getParentRoute: () => AuthenticatedBusinessRoute,
  } as any)
const AuthenticatedBusinessMembersRoute =
  AuthenticatedBusinessMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedBusinessRoute,
  } as any)
const AuthenticatedBusinessMemberPayoutsRoute =
  AuthenticatedBusinessMemberPayoutsRouteImport.update({
    id: '/member-payouts',
    path: '/member-payouts',
    getParentRoute: () => AuthenticatedBusinessRoute,
  } as any)
const AuthenticatedBusinessLeaderboardRoute =
  AuthenticatedBusinessLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedBusinessRoute,
  } as any)
const AuthenticatedBusinessEarningsRoute =
  AuthenticatedBusinessEarningsRouteImport.update({
    id: '/earnings',
    path: '/earnings',
    getParentRoute: () => AuthenticatedBusinessRoute,
  } as any)
const AuthenticatedBusinessActivityRoute =
  AuthenticatedBusinessActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedBusinessRoute,
  } as any)
const AuthenticatedAdminVersionsRoute =
  AuthenticatedAdminVersionsRouteImport.update({
    id: '/versions',
    path: '/versions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTicketsRoute =
  AuthenticatedAdminTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSessionsRoute =
  AuthenticatedAdminSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlatformsRoute =
  AuthenticatedAdminPlatformsRouteImport.update({
    id: '/platforms',
    path: '/platforms',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlansRoute = AuthenticatedAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPlanInfoRoute =
  AuthenticatedAdminPlanInfoRouteImport.update({
    id: '/plan-info',
    path: '/plan-info',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPayoutsRoute =
  AuthenticatedAdminPayoutsRouteImport.update({
    id: '/payouts',
    path: '/payouts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPayoutMethodsRoute =
  AuthenticatedAdminPayoutMethodsRouteImport.update({
    id: '/payout-methods',
    path: '/payout-methods',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOffersRoute =
  AuthenticatedAdminOffersRouteImport.update({
    id: '/offers',
    path: '/offers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFeaturesRoute =
  AuthenticatedAdminFeaturesRouteImport.update({
    id: '/features',
    path: '/features',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContactRoute =
  AuthenticatedAdminContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAffiliateRoute =
  AuthenticatedAdminAffiliateRouteImport.update({
    id: '/affiliate',
    path: '/affiliate',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/team': typeof TeamRouteWithChildren
  '/team-login': typeof TeamLoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/affiliate': typeof AuthenticatedAffiliateRoute
  '/business': typeof AuthenticatedBusinessRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/team/earning-info': typeof TeamEarningInfoRoute
  '/team/earnings': typeof TeamEarningsRoute
  '/team/leaderboard': typeof TeamLeaderboardRoute
  '/team/payments': typeof TeamPaymentsRoute
  '/team/profile': typeof TeamProfileRoute
  '/team/withdraw': typeof TeamWithdrawRoute
  '/team/': typeof TeamIndexRoute
  '/admin/affiliate': typeof AuthenticatedAdminAffiliateRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/contact': typeof AuthenticatedAdminContactRoute
  '/admin/features': typeof AuthenticatedAdminFeaturesRoute
  '/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/payout-methods': typeof AuthenticatedAdminPayoutMethodsRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/plan-info': typeof AuthenticatedAdminPlanInfoRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/platforms': typeof AuthenticatedAdminPlatformsRoute
  '/admin/sessions': typeof AuthenticatedAdminSessionsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/versions': typeof AuthenticatedAdminVersionsRoute
  '/business/activity': typeof AuthenticatedBusinessActivityRoute
  '/business/earnings': typeof AuthenticatedBusinessEarningsRoute
  '/business/leaderboard': typeof AuthenticatedBusinessLeaderboardRoute
  '/business/member-payouts': typeof AuthenticatedBusinessMemberPayoutsRoute
  '/business/members': typeof AuthenticatedBusinessMembersRoute
  '/business/recruitment': typeof AuthenticatedBusinessRecruitmentRoute
  '/business/rules': typeof AuthenticatedBusinessRulesRoute
  '/business/team-earnings': typeof AuthenticatedBusinessTeamEarningsRoute
  '/business/teams': typeof AuthenticatedBusinessTeamsRoute
  '/business/urls': typeof AuthenticatedBusinessUrlsRoute
  '/business/withdrawals': typeof AuthenticatedBusinessWithdrawalsRoute
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/dashboard/sessions': typeof AuthenticatedDashboardSessionsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/support': typeof AuthenticatedDashboardSupportRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/business/': typeof AuthenticatedBusinessIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/team-login': typeof TeamLoginRoute
  '/affiliate': typeof AuthenticatedAffiliateRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/team/earning-info': typeof TeamEarningInfoRoute
  '/team/earnings': typeof TeamEarningsRoute
  '/team/leaderboard': typeof TeamLeaderboardRoute
  '/team/payments': typeof TeamPaymentsRoute
  '/team/profile': typeof TeamProfileRoute
  '/team/withdraw': typeof TeamWithdrawRoute
  '/team': typeof TeamIndexRoute
  '/admin/affiliate': typeof AuthenticatedAdminAffiliateRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/contact': typeof AuthenticatedAdminContactRoute
  '/admin/features': typeof AuthenticatedAdminFeaturesRoute
  '/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/payout-methods': typeof AuthenticatedAdminPayoutMethodsRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/plan-info': typeof AuthenticatedAdminPlanInfoRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/platforms': typeof AuthenticatedAdminPlatformsRoute
  '/admin/sessions': typeof AuthenticatedAdminSessionsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/versions': typeof AuthenticatedAdminVersionsRoute
  '/business/activity': typeof AuthenticatedBusinessActivityRoute
  '/business/earnings': typeof AuthenticatedBusinessEarningsRoute
  '/business/leaderboard': typeof AuthenticatedBusinessLeaderboardRoute
  '/business/member-payouts': typeof AuthenticatedBusinessMemberPayoutsRoute
  '/business/members': typeof AuthenticatedBusinessMembersRoute
  '/business/recruitment': typeof AuthenticatedBusinessRecruitmentRoute
  '/business/rules': typeof AuthenticatedBusinessRulesRoute
  '/business/team-earnings': typeof AuthenticatedBusinessTeamEarningsRoute
  '/business/teams': typeof AuthenticatedBusinessTeamsRoute
  '/business/urls': typeof AuthenticatedBusinessUrlsRoute
  '/business/withdrawals': typeof AuthenticatedBusinessWithdrawalsRoute
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/dashboard/sessions': typeof AuthenticatedDashboardSessionsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/support': typeof AuthenticatedDashboardSupportRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/business': typeof AuthenticatedBusinessIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/team': typeof TeamRouteWithChildren
  '/team-login': typeof TeamLoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/affiliate': typeof AuthenticatedAffiliateRoute
  '/_authenticated/business': typeof AuthenticatedBusinessRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/team/earning-info': typeof TeamEarningInfoRoute
  '/team/earnings': typeof TeamEarningsRoute
  '/team/leaderboard': typeof TeamLeaderboardRoute
  '/team/payments': typeof TeamPaymentsRoute
  '/team/profile': typeof TeamProfileRoute
  '/team/withdraw': typeof TeamWithdrawRoute
  '/team/': typeof TeamIndexRoute
  '/_authenticated/admin/affiliate': typeof AuthenticatedAdminAffiliateRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/contact': typeof AuthenticatedAdminContactRoute
  '/_authenticated/admin/features': typeof AuthenticatedAdminFeaturesRoute
  '/_authenticated/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/payout-methods': typeof AuthenticatedAdminPayoutMethodsRoute
  '/_authenticated/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/_authenticated/admin/plan-info': typeof AuthenticatedAdminPlanInfoRoute
  '/_authenticated/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/_authenticated/admin/platforms': typeof AuthenticatedAdminPlatformsRoute
  '/_authenticated/admin/sessions': typeof AuthenticatedAdminSessionsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/versions': typeof AuthenticatedAdminVersionsRoute
  '/_authenticated/business/activity': typeof AuthenticatedBusinessActivityRoute
  '/_authenticated/business/earnings': typeof AuthenticatedBusinessEarningsRoute
  '/_authenticated/business/leaderboard': typeof AuthenticatedBusinessLeaderboardRoute
  '/_authenticated/business/member-payouts': typeof AuthenticatedBusinessMemberPayoutsRoute
  '/_authenticated/business/members': typeof AuthenticatedBusinessMembersRoute
  '/_authenticated/business/recruitment': typeof AuthenticatedBusinessRecruitmentRoute
  '/_authenticated/business/rules': typeof AuthenticatedBusinessRulesRoute
  '/_authenticated/business/team-earnings': typeof AuthenticatedBusinessTeamEarningsRoute
  '/_authenticated/business/teams': typeof AuthenticatedBusinessTeamsRoute
  '/_authenticated/business/urls': typeof AuthenticatedBusinessUrlsRoute
  '/_authenticated/business/withdrawals': typeof AuthenticatedBusinessWithdrawalsRoute
  '/_authenticated/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/_authenticated/dashboard/sessions': typeof AuthenticatedDashboardSessionsRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/support': typeof AuthenticatedDashboardSupportRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/business/': typeof AuthenticatedBusinessIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/download'
    | '/forgot-password'
    | '/location'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/team'
    | '/team-login'
    | '/admin'
    | '/affiliate'
    | '/business'
    | '/dashboard'
    | '/profile'
    | '/reviews'
    | '/team/earning-info'
    | '/team/earnings'
    | '/team/leaderboard'
    | '/team/payments'
    | '/team/profile'
    | '/team/withdraw'
    | '/team/'
    | '/admin/affiliate'
    | '/admin/announcements'
    | '/admin/contact'
    | '/admin/features'
    | '/admin/offers'
    | '/admin/payments'
    | '/admin/payout-methods'
    | '/admin/payouts'
    | '/admin/plan-info'
    | '/admin/plans'
    | '/admin/platforms'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/versions'
    | '/business/activity'
    | '/business/earnings'
    | '/business/leaderboard'
    | '/business/member-payouts'
    | '/business/members'
    | '/business/recruitment'
    | '/business/rules'
    | '/business/team-earnings'
    | '/business/teams'
    | '/business/urls'
    | '/business/withdrawals'
    | '/dashboard/billing'
    | '/dashboard/sessions'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/admin/'
    | '/business/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/download'
    | '/forgot-password'
    | '/location'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/team-login'
    | '/affiliate'
    | '/profile'
    | '/reviews'
    | '/team/earning-info'
    | '/team/earnings'
    | '/team/leaderboard'
    | '/team/payments'
    | '/team/profile'
    | '/team/withdraw'
    | '/team'
    | '/admin/affiliate'
    | '/admin/announcements'
    | '/admin/contact'
    | '/admin/features'
    | '/admin/offers'
    | '/admin/payments'
    | '/admin/payout-methods'
    | '/admin/payouts'
    | '/admin/plan-info'
    | '/admin/plans'
    | '/admin/platforms'
    | '/admin/sessions'
    | '/admin/settings'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/versions'
    | '/business/activity'
    | '/business/earnings'
    | '/business/leaderboard'
    | '/business/member-payouts'
    | '/business/members'
    | '/business/recruitment'
    | '/business/rules'
    | '/business/team-earnings'
    | '/business/teams'
    | '/business/urls'
    | '/business/withdrawals'
    | '/dashboard/billing'
    | '/dashboard/sessions'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/admin'
    | '/business'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/download'
    | '/forgot-password'
    | '/location'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/team'
    | '/team-login'
    | '/_authenticated/admin'
    | '/_authenticated/affiliate'
    | '/_authenticated/business'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/reviews'
    | '/team/earning-info'
    | '/team/earnings'
    | '/team/leaderboard'
    | '/team/payments'
    | '/team/profile'
    | '/team/withdraw'
    | '/team/'
    | '/_authenticated/admin/affiliate'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/contact'
    | '/_authenticated/admin/features'
    | '/_authenticated/admin/offers'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/payout-methods'
    | '/_authenticated/admin/payouts'
    | '/_authenticated/admin/plan-info'
    | '/_authenticated/admin/plans'
    | '/_authenticated/admin/platforms'
    | '/_authenticated/admin/sessions'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/tickets'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/versions'
    | '/_authenticated/business/activity'
    | '/_authenticated/business/earnings'
    | '/_authenticated/business/leaderboard'
    | '/_authenticated/business/member-payouts'
    | '/_authenticated/business/members'
    | '/_authenticated/business/recruitment'
    | '/_authenticated/business/rules'
    | '/_authenticated/business/team-earnings'
    | '/_authenticated/business/teams'
    | '/_authenticated/business/urls'
    | '/_authenticated/business/withdrawals'
    | '/_authenticated/dashboard/billing'
    | '/_authenticated/dashboard/sessions'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/support'
    | '/_authenticated/admin/'
    | '/_authenticated/business/'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DownloadRoute: typeof DownloadRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LocationRoute: typeof LocationRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TeamRoute: typeof TeamRouteWithChildren
  TeamLoginRoute: typeof TeamLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team-login': {
      id: '/team-login'
      path: '/team-login'
      fullPath: '/team-login'
      preLoaderRoute: typeof TeamLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/team/withdraw': {
      id: '/team/withdraw'
      path: '/withdraw'
      fullPath: '/team/withdraw'
      preLoaderRoute: typeof TeamWithdrawRouteImport
      parentRoute: typeof TeamRoute
    }
    '/team/profile': {
      id: '/team/profile'
      path: '/profile'
      fullPath: '/team/profile'
      preLoaderRoute: typeof TeamProfileRouteImport
      parentRoute: typeof TeamRoute
    }
    '/team/payments': {
      id: '/team/payments'
      path: '/payments'
      fullPath: '/team/payments'
      preLoaderRoute: typeof TeamPaymentsRouteImport
      parentRoute: typeof TeamRoute
    }
    '/team/leaderboard': {
      id: '/team/leaderboard'
      path: '/leaderboard'
      fullPath: '/team/leaderboard'
      preLoaderRoute: typeof TeamLeaderboardRouteImport
      parentRoute: typeof TeamRoute
    }
    '/team/earnings': {
      id: '/team/earnings'
      path: '/earnings'
      fullPath: '/team/earnings'
      preLoaderRoute: typeof TeamEarningsRouteImport
      parentRoute: typeof TeamRoute
    }
    '/team/earning-info': {
      id: '/team/earning-info'
      path: '/earning-info'
      fullPath: '/team/earning-info'
      preLoaderRoute: typeof TeamEarningInfoRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business': {
      id: '/_authenticated/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof AuthenticatedBusinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/affiliate': {
      id: '/_authenticated/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AuthenticatedAffiliateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/business/': {
      id: '/_authenticated/business/'
      path: '/'
      fullPath: '/business/'
      preLoaderRoute: typeof AuthenticatedBusinessIndexRouteImport
      parentRoute: typeof AuthenticatedBusinessRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/dashboard/support': {
      id: '/_authenticated/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof AuthenticatedDashboardSupportRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/sessions': {
      id: '/_authenticated/dashboard/sessions'
      path: '/sessions'
      fullPath: '/dashboard/sessions'
      preLoaderRoute: typeof AuthenticatedDashboardSessionsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/billing': {
      id: '/_authenticated/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof AuthenticatedDashboardBillingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/business/withdrawals': {
      id: '/_authenticated/business/withdrawals'
      path: '/withdrawals'
      fullPath: '/business/withdrawals'
      preLoaderRoute: typeof AuthenticatedBusinessWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedBusinessRoute
    }
    '/_authenticated/business/urls': {
      id: '/_authenticated/business/urls'
      path: '/urls'
      fullPath: '/business/urls'
      preLoaderRoute: typeof AuthenticatedBusinessUrlsRouteImport
      parentRoute: typeof AuthenticatedBusinessRoute
    }
    '/_authenticated/business/teams': {
      id: '/_authenticated/business/teams'
      path: '/teams'
      fullPath: '/business/teams'
      preLoaderRoute: typeof AuthenticatedBusinessTeamsRouteImport
      parentRoute: typeof AuthenticatedBusinessRoute
    }
    '/_authenticated/business/team-earnings': {
      id: '/_authenticated/business/team-earnings'
      path: '/team-earnings'
      fullPath: '/business/team-earnings'
      preLoaderRoute: typeof AuthenticatedBusinessTeamEarningsRouteImport
      parentRoute: typeof AuthenticatedBusinessRoute
    }
    '/_authenticated/business/rules': {
      id: '/_authenticated/business/rules'
      path: '/rules'
      fullPath: '/business/rules'
      preLoaderRoute: typeof AuthenticatedBusinessRulesRouteImport
      parentRoute: typeof AuthenticatedBusinessRoute
    }
    '/_authenticated/business/recruitment': {
      id: '/_authenticated/business/recruitment'
      path: '/recruitment'
      fullPath: '/business/recruitment'
      preLoaderRoute: typeof AuthenticatedBusinessRecruitmentRouteImport
      parentRoute: typeof AuthenticatedBusinessRoute
    }
    '/_authenticated/business/members': {
      id: '/_authenticated/business/members'
      path: '/members'
      fullPath: '/business/members'
      preLoaderRoute: typeof AuthenticatedBusinessMembersRouteImport
      parentRoute: typeof AuthenticatedBusinessRoute
    }
    '/_authenticated/business/member-payouts': {
      id: '/_authenticated/business/member-payouts'
      path: '/member-payouts'
      fullPath: '/business/member-payouts'
      preLoaderRoute: typeof AuthenticatedBusinessMemberPayoutsRouteImport
      parentRoute: typeof AuthenticatedBusinessRoute
    }
    '/_authenticated/business/leaderboard': {
      id: '/_authenticated/business/leaderboard'
      path: '/leaderboard'
      fullPath: '/business/leaderboard'
      preLoaderRoute: typeof AuthenticatedBusinessLeaderboardRouteImport
      parentRoute: typeof AuthenticatedBusinessRoute
    }
    '/_authenticated/business/earnings': {
      id: '/_authenticated/business/earnings'
      path: '/earnings'
      fullPath: '/business/earnings'
      preLoaderRoute: typeof AuthenticatedBusinessEarningsRouteImport
      parentRoute: typeof AuthenticatedBusinessRoute
    }
    '/_authenticated/business/activity': {
      id: '/_authenticated/business/activity'
      path: '/activity'
      fullPath: '/business/activity'
      preLoaderRoute: typeof AuthenticatedBusinessActivityRouteImport
      parentRoute: typeof AuthenticatedBusinessRoute
    }
    '/_authenticated/admin/versions': {
      id: '/_authenticated/admin/versions'
      path: '/versions'
      fullPath: '/admin/versions'
      preLoaderRoute: typeof AuthenticatedAdminVersionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tickets': {
      id: '/_authenticated/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AuthenticatedAdminTicketsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sessions': {
      id: '/_authenticated/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AuthenticatedAdminSessionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/platforms': {
      id: '/_authenticated/admin/platforms'
      path: '/platforms'
      fullPath: '/admin/platforms'
      preLoaderRoute: typeof AuthenticatedAdminPlatformsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/plans': {
      id: '/_authenticated/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AuthenticatedAdminPlansRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/plan-info': {
      id: '/_authenticated/admin/plan-info'
      path: '/plan-info'
      fullPath: '/admin/plan-info'
      preLoaderRoute: typeof AuthenticatedAdminPlanInfoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payouts': {
      id: '/_authenticated/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AuthenticatedAdminPayoutsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payout-methods': {
      id: '/_authenticated/admin/payout-methods'
      path: '/payout-methods'
      fullPath: '/admin/payout-methods'
      preLoaderRoute: typeof AuthenticatedAdminPayoutMethodsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/offers': {
      id: '/_authenticated/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AuthenticatedAdminOffersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/features': {
      id: '/_authenticated/admin/features'
      path: '/features'
      fullPath: '/admin/features'
      preLoaderRoute: typeof AuthenticatedAdminFeaturesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contact': {
      id: '/_authenticated/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AuthenticatedAdminContactRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/affiliate': {
      id: '/_authenticated/admin/affiliate'
      path: '/affiliate'
      fullPath: '/admin/affiliate'
      preLoaderRoute: typeof AuthenticatedAdminAffiliateRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAffiliateRoute: typeof AuthenticatedAdminAffiliateRoute
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminContactRoute: typeof AuthenticatedAdminContactRoute
  AuthenticatedAdminFeaturesRoute: typeof AuthenticatedAdminFeaturesRoute
  AuthenticatedAdminOffersRoute: typeof AuthenticatedAdminOffersRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPayoutMethodsRoute: typeof AuthenticatedAdminPayoutMethodsRoute
  AuthenticatedAdminPayoutsRoute: typeof AuthenticatedAdminPayoutsRoute
  AuthenticatedAdminPlanInfoRoute: typeof AuthenticatedAdminPlanInfoRoute
  AuthenticatedAdminPlansRoute: typeof AuthenticatedAdminPlansRoute
  AuthenticatedAdminPlatformsRoute: typeof AuthenticatedAdminPlatformsRoute
  AuthenticatedAdminSessionsRoute: typeof AuthenticatedAdminSessionsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTicketsRoute: typeof AuthenticatedAdminTicketsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVersionsRoute: typeof AuthenticatedAdminVersionsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAffiliateRoute: AuthenticatedAdminAffiliateRoute,
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminContactRoute: AuthenticatedAdminContactRoute,
  AuthenticatedAdminFeaturesRoute: AuthenticatedAdminFeaturesRoute,
  AuthenticatedAdminOffersRoute: AuthenticatedAdminOffersRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminPayoutMethodsRoute: AuthenticatedAdminPayoutMethodsRoute,
  AuthenticatedAdminPayoutsRoute: AuthenticatedAdminPayoutsRoute,
  AuthenticatedAdminPlanInfoRoute: AuthenticatedAdminPlanInfoRoute,
  AuthenticatedAdminPlansRoute: AuthenticatedAdminPlansRoute,
  AuthenticatedAdminPlatformsRoute: AuthenticatedAdminPlatformsRoute,
  AuthenticatedAdminSessionsRoute: AuthenticatedAdminSessionsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTicketsRoute: AuthenticatedAdminTicketsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminVersionsRoute: AuthenticatedAdminVersionsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedBusinessRouteChildren {
  AuthenticatedBusinessActivityRoute: typeof AuthenticatedBusinessActivityRoute
  AuthenticatedBusinessEarningsRoute: typeof AuthenticatedBusinessEarningsRoute
  AuthenticatedBusinessLeaderboardRoute: typeof AuthenticatedBusinessLeaderboardRoute
  AuthenticatedBusinessMemberPayoutsRoute: typeof AuthenticatedBusinessMemberPayoutsRoute
  AuthenticatedBusinessMembersRoute: typeof AuthenticatedBusinessMembersRoute
  AuthenticatedBusinessRecruitmentRoute: typeof AuthenticatedBusinessRecruitmentRoute
  AuthenticatedBusinessRulesRoute: typeof AuthenticatedBusinessRulesRoute
  AuthenticatedBusinessTeamEarningsRoute: typeof AuthenticatedBusinessTeamEarningsRoute
  AuthenticatedBusinessTeamsRoute: typeof AuthenticatedBusinessTeamsRoute
  AuthenticatedBusinessUrlsRoute: typeof AuthenticatedBusinessUrlsRoute
  AuthenticatedBusinessWithdrawalsRoute: typeof AuthenticatedBusinessWithdrawalsRoute
  AuthenticatedBusinessIndexRoute: typeof AuthenticatedBusinessIndexRoute
}

const AuthenticatedBusinessRouteChildren: AuthenticatedBusinessRouteChildren = {
  AuthenticatedBusinessActivityRoute: AuthenticatedBusinessActivityRoute,
  AuthenticatedBusinessEarningsRoute: AuthenticatedBusinessEarningsRoute,
  AuthenticatedBusinessLeaderboardRoute: AuthenticatedBusinessLeaderboardRoute,
  AuthenticatedBusinessMemberPayoutsRoute:
    AuthenticatedBusinessMemberPayoutsRoute,
  AuthenticatedBusinessMembersRoute: AuthenticatedBusinessMembersRoute,
  AuthenticatedBusinessRecruitmentRoute: AuthenticatedBusinessRecruitmentRoute,
  AuthenticatedBusinessRulesRoute: AuthenticatedBusinessRulesRoute,
  AuthenticatedBusinessTeamEarningsRoute:
    AuthenticatedBusinessTeamEarningsRoute,
  AuthenticatedBusinessTeamsRoute: AuthenticatedBusinessTeamsRoute,
  AuthenticatedBusinessUrlsRoute: AuthenticatedBusinessUrlsRoute,
  AuthenticatedBusinessWithdrawalsRoute: AuthenticatedBusinessWithdrawalsRoute,
  AuthenticatedBusinessIndexRoute: AuthenticatedBusinessIndexRoute,
}

const AuthenticatedBusinessRouteWithChildren =
  AuthenticatedBusinessRoute._addFileChildren(
    AuthenticatedBusinessRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardBillingRoute: typeof AuthenticatedDashboardBillingRoute
  AuthenticatedDashboardSessionsRoute: typeof AuthenticatedDashboardSessionsRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardSupportRoute: typeof AuthenticatedDashboardSupportRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardBillingRoute: AuthenticatedDashboardBillingRoute,
    AuthenticatedDashboardSessionsRoute: AuthenticatedDashboardSessionsRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardSupportRoute: AuthenticatedDashboardSupportRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAffiliateRoute: typeof AuthenticatedAffiliateRoute
  AuthenticatedBusinessRoute: typeof AuthenticatedBusinessRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAffiliateRoute: AuthenticatedAffiliateRoute,
  AuthenticatedBusinessRoute: AuthenticatedBusinessRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface TeamRouteChildren {
  TeamEarningInfoRoute: typeof TeamEarningInfoRoute
  TeamEarningsRoute: typeof TeamEarningsRoute
  TeamLeaderboardRoute: typeof TeamLeaderboardRoute
  TeamPaymentsRoute: typeof TeamPaymentsRoute
  TeamProfileRoute: typeof TeamProfileRoute
  TeamWithdrawRoute: typeof TeamWithdrawRoute
  TeamIndexRoute: typeof TeamIndexRoute
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamEarningInfoRoute: TeamEarningInfoRoute,
  TeamEarningsRoute: TeamEarningsRoute,
  TeamLeaderboardRoute: TeamLeaderboardRoute,
  TeamPaymentsRoute: TeamPaymentsRoute,
  TeamProfileRoute: TeamProfileRoute,
  TeamWithdrawRoute: TeamWithdrawRoute,
  TeamIndexRoute: TeamIndexRoute,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DownloadRoute: DownloadRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LocationRoute: LocationRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TeamRoute: TeamRouteWithChildren,
  TeamLoginRoute: TeamLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
